name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: PHP ${{ matrix.php }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: ['8.3']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: xdebug

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: --prefer-dist --no-progress --no-interaction

      - name: Run tests
        run: composer test

      - name: Run static analysis
        run: composer stan

      - name: Coding standards (dry-run)
        run: composer cs-check

  coverage:
    name: Coverage (PHP 8.3)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          coverage: xdebug

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: --prefer-dist --no-progress --no-interaction

      - name: Run tests with coverage
        run: |
          vendor/bin/pest --coverage --coverage-clover=coverage/clover.xml

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-clover
          path: coverage/clover.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage/clover.xml
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

